# -*- coding: utf-8 -*-
"""Teste1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18xQflMBM5Syo0C05WU_KfO02BnssTShO
"""

import requests

def main():
  print('CEPython')

  nome = input('digite o nome para consulta: ')

  while len(nome) != 8:
    print('quantidade de digito invalido!')
    nome = input('digite o NOME para a consulta')

  
  request = requests.get('https://servicodados.ibge.gov.br/api/v2/censos/nomes/ranking'.format(nome))
  endereco = request.json()

 
  if 'erro' not in endereco :
    print('==> NOME ENCONTRADO <==')
    print('NOME: {}'.format(endereco['nome']))
    print('ibge: {}'.format(endereco['ibge']))
    print('FREQUENCIA: {}'.format(endereco['ibge']))

  else:
     print('{}: NOME invalido'.format(nome))

  opcao = int(input('Deseja realizar outra consulta?\n [1]Sim\n [2]Sair\n'))
  if opcao == 1:
    main()
  else:
      print('Até mais!!!')

 

if __name__ == '__main__':
  main()